preprocessing:
  output_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/retrospective_oau/features/h-optimus-0/"
  wsi_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/retrospective_oau/raw"
  extractor: "h-optimus-0"
  device: "cuda:0"
  cache_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/retrospective_oau/.cache"
  max_workers: 16
  default_slide_mpp: 0.259965
