#!/bin/bash
#SBATCH --job-name=histobistro_baseline
#SBATCH --partition=nvidia-A4000-20
#SBATCH --output=/lab/barcheese01/mdiberna/ARGO-DeepMSI/logs/baseline_testing/%x_%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --gres=gpu:1
#SBATCH --time=4:00:00

#######################################################################################
# Stage 5: Baseline Testing with HistoBistro
#
# Usage:
#   sbatch scripts/5_baseline_testing.sh
#
# Prerequisites:
#   - Stage 4 must be run for ctranspath model first
#   - This auto-generates HistoBistro-format tables
#
# This script:
#   - Tests pre-trained HistoBistro MSI model on CTransPath features
#   - Uses tables auto-generated by Stage 4 (feature validation for ctranspath)
#   - Stage 4 creates all_slide_table_histobistro.csv with FILENAME = stems only
#   - HistoBistro recursively finds h5 files in results/stage3_features/ctranspath/
#   - Outputs predictions to results/stage5_baseline/
#
# Expected performance: NPV ~0.99 (from published results)
# If performance is significantly lower, indicates data quality issues
#######################################################################################

echo "================================="
echo "HISTOBISTRO BASELINE TESTING"
echo "Time: $(date)"
echo "================================="

# Define base directory
BASE_DIR="/lab/barcheese01/mdiberna/ARGO-DeepMSI"
cd "$BASE_DIR"

# Source bashrc for conda
source ~/.bashrc

# Activate HistoBistro environment
echo "Activating HistoBistro environment..."
conda activate histobistro

# Print GPU information
echo "==== GPU INFO ===="
nvidia-smi
echo "=================="

# Check PyTorch GPU access
echo "==== PYTORCH GPU CHECK ===="
python -c "
import torch
print('CUDA available:', torch.cuda.is_available())
print('CUDA device count:', torch.cuda.device_count())
if torch.cuda.is_available():
    print('CUDA current device:', torch.cuda.current_device())
    print('CUDA device name:', torch.cuda.get_device_name(0))
"
echo "==========================="

# Define paths (all tables prepared by Stage 4)
CLINICAL_TABLE="$BASE_DIR/results/stage4_feature_validation/ctranspath/tables/all_clinical_table.csv"
HISTOBISTRO_SLIDE_TABLE="$BASE_DIR/results/stage4_feature_validation/ctranspath/tables/all_slide_table_histobistro.csv"
CONFIG_FILE="$BASE_DIR/configs/histobistro/config.yaml"
DATA_CONFIG_FILE="$BASE_DIR/configs/histobistro/data_config.yaml"
MODEL_PATH="$BASE_DIR/HistoBistro/CancerCellCRCTransformer/trained_models/MSI_high_CRC_model.pth"

# Create directories
mkdir -p "$BASE_DIR/results/stage5_baseline"
mkdir -p "$BASE_DIR/logs/baseline_testing"

# Check that input files exist
if [ ! -f "$CLINICAL_TABLE" ]; then
    echo "ERROR: Clinical table not found: $CLINICAL_TABLE"
    echo "Run Stage 4 (feature validation for ctranspath) first"
    exit 1
fi

if [ ! -f "$HISTOBISTRO_SLIDE_TABLE" ]; then
    echo "ERROR: HistoBistro slide table not found: $HISTOBISTRO_SLIDE_TABLE"
    echo "Run Stage 4 (feature validation for ctranspath) first"
    echo "Stage 4 auto-generates this table when processing ctranspath model"
    exit 1
fi

if [ ! -f "$MODEL_PATH" ]; then
    echo "ERROR: Pre-trained model not found: $MODEL_PATH"
    echo "Check HistoBistro installation"
    exit 1
fi

echo "==== USING PRE-GENERATED TABLES FROM STAGE 4 ===="
echo "Clinical table: $CLINICAL_TABLE"
echo "Slide table (HistoBistro format): $HISTOBISTRO_SLIDE_TABLE"
echo "=================================================="
echo ""

# Verify config files exist
if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: Config file not found: $CONFIG_FILE"
    exit 1
fi

if [ ! -f "$DATA_CONFIG_FILE" ]; then
    echo "ERROR: Data config file not found: $DATA_CONFIG_FILE"
    exit 1
fi

echo "==== RUNNING HISTOBISTRO INFERENCE ===="
echo "Config: $CONFIG_FILE"
echo "Data config: $DATA_CONFIG_FILE"
echo "Model: $MODEL_PATH"
echo "========================================"

# Change to HistoBistro directory
cd "$BASE_DIR/HistoBistro"

# Run HistoBistro test.py
python test.py \
    --model_path "$MODEL_PATH" \
    --name "msi_baseline_argo" \
    --config_file "$CONFIG_FILE" \
    --data_config "$DATA_CONFIG_FILE"

exit_code=$?

echo "================================="
echo "BASELINE TESTING COMPLETED"
echo "Exit code: $exit_code"
echo "Time: $(date)"
echo "================================="

if [ $exit_code -eq 0 ]; then
    echo "✓ HistoBistro baseline testing completed successfully"
    echo ""
    echo "Results saved to: $BASE_DIR/results/stage5_baseline/"
    echo ""
    echo "Expected performance: NPV ~0.99 (sensitivity ~0.99)"
    echo "Check results against published benchmarks to validate data quality"
else
    echo "✗ HistoBistro baseline testing failed (exit code: $exit_code)"
    echo "Check logs for errors"
fi

exit $exit_code
