preprocessing:
  output_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/LUTH/features/h-optimus-1/"
  wsi_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/LUTH/raw"
  extractor: "h-optimus-1"
  device: "cuda:0"
  cache_dir: "/lab/barcheese01/mdiberna/ARGO-DeepMSI/data/LUTH/.cache"
  max_workers: 16
  default_slide_mpp: 0.259965
